### ISSUE TITLE
"composer require reshadman/lmauth" doesn't work on Git Bash

### ISSUE THREAD

**Issue by akasham67** [reshadman/laravel-mongo-auth#2]
"composer require reshadman/lmauth" doesn't work on Git Bash. It's say the following Error message:

 [InvalidArgumentException]
  Could not find package reshadman/lmauth at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability. 

How do I solve this? Any Idea?

**Comment by ederribeiro** [comment]
For the next one: 

> composer require reshadman/laravel-mongo-auth
